language: node_js
node_js:
  - "14"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules
     - /home/travis/.cache/Cypress

install:
  - npm install
  - npm install --force cypress@latest

script:
  - npm run test-travis -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm start & wait-on http://localhost:4200
  # try to verify cypress installation, as there have been issues with Cypress on Travis
  - npm run cypress:verify
  - npm run cypress:run
