language: node_js
node_js:
  - "14"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules
     - /home/travis/.cache/Cypress

install:
  - npm install

script:
  - npm run test-travis -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm start & wait-on http://localhost:4200
  - npm run cypress:run
